version: '3.8'

services:
  frontend:
    image: douglasvdmerwe/dev-app-image:${{ env.IMAGE_TAG_FE }}
    container_name: app-container
    ports:
      - 3000:3000
    restart: unless-stopped  # Automatically restart the container unless stopped intentionally
    environment:
      - NODE_ENV=production  # Set the Node.js environment to production

  backend:
    image: douglasvdmerwe/dev-api-image:${{ env.IMAGE_TAG_BE }}
    container_name: api-container
    ports:
      - 5001:5001
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${{ secrets.POSTGRES_USER }}
      - POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
    depends_on:
      - database  # Wait for the database service to be ready before starting the backend

  database:
    image: postgres:12.8-alpine  # Upgrade to a newer version of PostgreSQL
    restart: unless-stopped
    container_name: db-container
    environment:
      - POSTGRES_USER=${{ secrets.POSTGRES_USER }}
      - POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
