name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up environment variables
        id: env
        run: echo "IMAGE_TAG=douglasvdmerwe/dev-app-image:$(date +%s)" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build ./frontend --file frontend/Dockerfile --tag ${{ env.IMAGE_TAG }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        run: docker push ${{ env.IMAGE_TAG }}
