name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          if [[ -n $(git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} -- frontend/) ]]; then
            echo "IMAGE_TAG_FE=douglasvdmerwe/dev-app-image:${{ github.sha }}" >> $GITHUB_ENV
          fi
          if [[ -n $(git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }} -- backend/) ]]; then
            echo "IMAGE_TAG_BE=douglasvdmerwe/dev-api-image:${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Build the Docker image FE
        run: |
          if [[ -n ${{ env.IMAGE_TAG_FE }} ]]; then
            docker build ./frontend --file frontend/Dockerfile --tag ${{ env.IMAGE_TAG_FE }}
          fi

      - name: Build the Docker image BE
        run: |
          if [[ -n ${{ env.IMAGE_TAG_BE }} ]]; then
            docker build ./backend --file backend/Dockerfile --tag ${{ env.IMAGE_TAG_BE }}
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub FE
        run: |
          if [[ -n ${{ env.IMAGE_TAG_FE }} ]]; then
            docker push ${{ env.IMAGE_TAG_FE }}
          fi

      - name: Push to Docker Hub BE
        run: |
          if [[ -n ${{ env.IMAGE_TAG_BE }} ]]; then
            docker push ${{ env.IMAGE_TAG_BE }}
          fi
