name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "IMAGE_TAG_FE=douglasvdmerwe/dev-app-image:$(date +%s)" >> $GITHUB_ENV
          echo "IMAGE_TAG_BE=douglasvdmerwe/dev-api-image:$(date +%s)" >> $GITHUB_ENV

      - name: Build the Docker image FE
        run: docker build ./frontend --file frontend/Dockerfile --tag ${{ env.IMAGE_TAG_FE }}

      - name: Build the Docker image BE
        run: docker build ./backend --file backend/Dockerfile --tag ${{ env.IMAGE_TAG_BE }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub FE
        run: docker push ${{ env.IMAGE_TAG_FE }}

      - name: Push to Docker Hub BE
        run: docker push ${{ env.IMAGE_TAG_BE }}
